// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPXweq31bTx9HBmn74dfxf3bT5d7yMkk',
    appId: '1:147405246058:web:e1723ea1c31fbf1aa48413',
    messagingSenderId: '147405246058',
    projectId: 'com-18b90-1e57f',
    authDomain: 'com-18b90-1e57f.firebaseapp.com',
    storageBucket: 'com-18b90-1e57f.firebasestorage.app',
    measurementId: 'G-TZEZFNX63Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdGQaTTFMoWN_IJQyLoFsXr76g5XhvR8',
    appId: '1:147405246058:android:9736cfe54d54edf2a48413',
    messagingSenderId: '147405246058',
    projectId: 'com-18b90-1e57f',
    storageBucket: 'com-18b90-1e57f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5EOeHiF-vjQa2_mebk1HXHgIKIbzcPZI',
    appId: '1:147405246058:ios:6d804bb9114d79e2a48413',
    messagingSenderId: '147405246058',
    projectId: 'com-18b90-1e57f',
    storageBucket: 'com-18b90-1e57f.firebasestorage.app',
    iosBundleId: 'com.luandevfullstack.crtl02',
  );

}